# wrangler.toml
name = "personal-blog"
compatibility_date = "2025-09-05"

[build]
command = "./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

# Optional: Custom domain configuration
[route]
pattern = "blog.ashlin.dev/*"
zone_name = "blog.ashlin.dev"

